spring:
  servlet:
    # file ??? ?? ?? (????? ?? ?? ? Spring boot? ????? 1MB? ???)
    multipart:
      max-file-size: 10MB  # ?? ?? ??
      max-request-size: 10MB  # ?? ?? ??

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop                # ddl ?? ?? ??
    properties:
      hibernate:
        format_sql: true             # ??????? ??? SQL? ??? ? ?? ?? ??
        use_sql_comments: true
        show_sql: true               # ??????? ??? SQL? ??
        jdbc:
          batch_size: 100              #   insert/update ??? ??? ???? ??? DB? ?? ? ?? ??
        default_batch_fetch_size: 100

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # DB ????
    url: jdbc:mysql://localhost:3306/Tokidoki?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true       # ?????? URL
    username: ssafy                     # ?????? ???
    password: ssafy                       # ?????? ?? ????

  # NoSQL setting
  data:
    # Redis setting
    redis:
      host: localhost
      port: 6379

# jwt setting
jwt:
  accessKey: TestAccessKey111111122222222223333333333333aaaaaaaaabbbbbbbbccccccccdddddddddfqwrqwfqwifjaisfjoihfoiqwflasjdglkkjasdlgjlkasdgjiowejgliasjglasjdgio
  refreshKey: TestRefreshKey111111122222222223333333333333aaaaaaaaabbbbbbbbccccccccdddddddddfqwrqwfqwifjaisfjoihfoiqwflasjdglkkjasdlgjlkasdgjiowejgliasjglasjdgio
  accessExpiration: PT60M  # 60? (PT60M)
  refreshExpiration: PT1080M  # 10080? (7?) (PT10080M)

# log ??
logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      org.hibernate.SQLQuery: debug
